name: Continuous Integration

on:
  push:
    branches:
      - "main"

env:
  NODE_VERSION: 18
  CI: true
  CYPRESS_CACHE_FOLDER: cypress_cache
  NUMBER_OF_RUNNERS: 7

jobs:
  component-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current commit
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Use pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
            ~/.cache/Cypress
          key: pnpm-with-cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-with-cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Component Tests
        run: pnpm run test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Library
        run: pnpm run build
