name: Continuous Deployment

on:
  workflow_dispatch:
    branches:
      - "main"
  push:
    branches:
      - "beta"

env:
  NODE_VERSION: 18
  CI: true
  CYPRESS_CACHE_FOLDER: cypress_cache
  NUMBER_OF_RUNNERS: 7

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write
      pull-requests: write

    steps:
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Use pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
            ~/.cache/Cypress
          key: pnpm-with-cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-with-cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Component Tests
        run: pnpm run test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Library
        run: pnpm run build

      - name: Release
        if: ${{ !contains(github.event.head_commit.message, format('chore(release-skip){0}', ':')) }}
        run: |
          npx -p @semantic-release/exec -p semantic-release semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
