name: Continuous Deployment

on:
  workflow_dispatch:
    branches:
      - "main"
  push:
    branches:
      - "beta"

env:
    NODE_VERSION: 16
    CI: true
    CYPRESS_CACHE_FOLDER: cypress_cache
    NUMBER_OF_RUNNERS: 7

jobs:
    publish:
        runs-on: ubuntu-latest

        permissions:
            packages: write
            contents: write

        steps:
            -   name: Checkout current commit
                uses: actions/checkout@v3

            -   name: Use Node.js ${{ env.NODE_VERSION }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ env.NODE_VERSION }}

            -   name: Cache dependencies
                id: npm_cache
                uses: actions/cache@v3
                with:
                    path: |
                        node_modules
                        ${{ env.CYPRESS_CACHE_FOLDER }}
                    key: node_modules-${{ hashFiles('package-lock.json') }}
                    restore-keys: node_modules-

            -   name: Install dependencies
                if: steps.npm_cache.outputs.cache-hit != 'true'
                run: npm ci

            -   name: Component Tests
                run: npm run test
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build Library
                run: npm run build

            -   name: Release
                run: npx semantic-release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            -   name: Testing git
                uses: peter-evans/create-pull-request@v4
                with:
                    title: 'chore: update package.json [ci skip]'
                    commit-message: 'chore: update package.json [ci skip]'
                    branch: chore/auto_update_package_json_version
                    delete-branch: true
                    add-paths: |
                        package.json
                        package-lock.json
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
