name: Pull Request Title

on:
    pull_request:
        types: 
            - opened
            - edited
            - reopened
            - synchronize
        branches:
            - 'main'
            - 'beta'

jobs:
    pr-title-validation:
        runs-on: ubuntu-latest
        steps:
            -   uses: amannn/action-semantic-pull-request@v5
                env: 
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
