name: Pull Request

on:
    pull_request:
        branches:
            - 'main'
            - 'beta'

env:
    NODE_VERSION: 16
    CI: true
    CYPRESS_CACHE_FOLDER: cypress_cache
    NUMBER_OF_RUNNERS: 7

jobs:
    pr-title-validation:
        runs-on: ubuntu-latest
        steps:
            -   uses: amannn/action-semantic-pull-request@v5
                env: 
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
