name: Pull Request Merged

on:
  pull_request:
    branches:
      - "main"
    types: [closed]

jobs:
  create-beta-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == 'true'

    steps:
      - name: Checkout current commit on main branch
        uses: actions/checkout@v3
        with: 
          ref: main

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache dependencies
        id: npm_cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ${{ env.CYPRESS_CACHE_FOLDER }}
          key: node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node_modules-

      - name: Install dependencies
        if: steps.npm_cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Component Tests
        run: npm run test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Create Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
