name: Release Preview

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - "main"

env:
  NODE_VERSION: 16
  CI: true
  CYPRESS_CACHE_FOLDER: cypress_cache
  NUMBER_OF_RUNNERS: 7

jobs:
  preview:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout current commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release preview
        run: |
          echo "Current branch: ${{github.ref_name}}"
          unset GITHUB_ACTIONS && npx semantic-release --dry-run --no-ci --branches main,106/merge
