name: Release Preview

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - "main"

env:
  NODE_VERSION: 18
  CI: true
  CYPRESS_CACHE_FOLDER: cypress_cache
  NUMBER_OF_RUNNERS: 7

jobs:
  preview:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout current commit
        uses: actions/checkout@v3

      - name: Create release-preview branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "release-preview"

      - name: Checkout release-preview branch
        uses: actions/checkout@v3
        with:
          ref: release-preview

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache dependencies
        id: npm_cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ${{ env.CYPRESS_CACHE_FOLDER }}
          key: node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node_modules-

      - name: Install dependencies
        if: steps.npm_cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Save release preview to job Summary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          unset GITHUB_ACTIONS && npx -p @semantic-release/exec -p semantic-release semantic-release --dry-run --no-ci --branches main,release-preview @semantic-release/exec --generateNotesCmd 'echo "${nextRelease.notes}" >> $GITHUB_STEP_SUMMARY'

      - name: Checkout PR commit
        uses: actions/checkout@v3

      - name: Delete release-preview branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: release-preview
