name: Release Preview

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - "main"

env:
  NODE_VERSION: 16
  CI: true
  CYPRESS_CACHE_FOLDER: cypress_cache
  NUMBER_OF_RUNNERS: 7

jobs:
  preview:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout current commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache dependencies
        id: npm_cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ${{ env.CYPRESS_CACHE_FOLDER }}
          key: node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node_modules-

      - name: Install dependencies
        if: steps.npm_cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Component Tests
        run: npm run test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Library
        run: npm run build

      - name: Release
        if: ${{ !contains(github.event.head_commit.message, format('chore(release-skip){0}', ':')) }}
        uses: guilhermetod/semantic-release-notes-preview@v1.0.0

      - name: Comment release notes preview
        if: steps.build-release-notes.outputs.releaseNotes
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ## 👋 Hey there!
            Thank you for you contribution. Below is a preview of the release notes if your PR gets merged.
            Please, make sure it includes all your significant changes with descriptive messages.
            Keep in mind that release notes are automatically generated from the commit messages according to [conventional commits](https://www.conventionalcommits.org/).
            If you feel like you need to change anything, please take a look into [this guide](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#addressing-review-feedback) to learn how you can fixup your commits.

            ---

            ${{ steps.build-release-notes.outputs.releaseNotes }}
